### ISSUE TITLE
check-zone.py doesn't catch the missing dot(.) in the end for the cname records,

### ISSUE THREAD

**Issue by mkumatag** [kubernetes/k8s.io#3173]
e.g: this https://github.com/kubernetes/k8s.io/pull/3164 got merged but later post submit [job failed](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-k8sio-dns/1469456044001333248) with the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/octodns-sync", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/octodns/cmds/sync.py", line 38, in main
    manager.sync(eligible_zones=args.zone, eligible_targets=args.target,
  File "/usr/local/lib/python3.8/site-packages/octodns/manager.py", line 315, in sync
    plans = [p for f in futures for p in f.result()]
  File "/usr/local/lib/python3.8/site-packages/octodns/manager.py", line 315, in <listcomp>
    plans = [p for f in futures for p in f.result()]
  File "/usr/local/lib/python3.8/site-packages/octodns/manager.py", line 56, in result
    return self.func(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/octodns/manager.py", line 230, in _populate_and_plan
    source.populate(zone)
  File "/usr/local/lib/python3.8/site-packages/octodns/provider/yaml.py", line 77, in populate
    self._populate_from_file(filename, zone, lenient)
  File "/usr/local/lib/python3.8/site-packages/octodns/provider/yaml.py", line 60, in _populate_from_file
    record = Record.new(zone, name, d, source=self,
  File "/usr/local/lib/python3.8/site-packages/octodns/record/__init__.py", line 118, in new
    raise ValidationError(fqdn, reasons)
octodns.record.ValidationError: Invalid record cluster-api-ibmcloud.sigs.canary.k8s.io.
  - CNAME value "kubernetes-sigs-cluster-api-ibmcloud.netlify.app" missing trailing .
make: *** [Makefile:63: push-local] Error 2
```

**Comment by ameukam** [comment]
@mkumatag please, go for it.

/assign @mkumatag

**Comment by BenTheElder** [comment]
I think we're not even running check-zone.py in CI?

**Comment by BenTheElder** [comment]
Also currently the check script isn't in sync with the production python deps.

I did some fixup and it seems _slow_, is anyone running this at all?

**Comment by BenTheElder** [comment]
... and further, that script is intended to check the live endpoints, we probably need an entirely new script that just validates the config.

**Comment by mkumatag** [comment]
> ... and further, that script is intended to check the live endpoints (?), we probably need an entirely new script that just validates the config.

Yes, i did explore that a bit, need to different approach all together, we can do this a built-in validate library..

**Comment by mkumatag** [comment]
@BenTheElder my initial try to fix this issue - https://github.com/kubernetes/k8s.io/pull/3339, ptal
